# Generated by Django 3.2.19 on 2023-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percentage',
            field=models.IntegerField(default=10),
        ),
    ]
