# Generated by Django 3.2.19 on 2023-09-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfer_percentage',
            field=models.IntegerField(default=10),
        ),
    ]
