# Generated by Django 3.2.19 on 2023-09-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_transfer_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='percentage',
            new_name='crypto_percentage',
        ),
    ]
