# Generated by Django 4.2.1 on 2023-05-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_remove_wallet_balance_remove_wallet_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencybalance',
            unique_together={('wallet', 'currency')},
        ),
    ]
