# Generated by Django 3.2.19 on 2023-05-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_auto_20230523_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencybalance',
            name='show_pending',
            field=models.BooleanField(default=False),
        ),
    ]
